name: p310
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - appdirs=1.4.4
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - babel=2.11.0
  - backcall=0.2.0
  - beautifulsoup4=4.12.2
  - blas=1.0
  - bleach=4.1.0
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2023.05.30
  - cffi=1.15.1
  - contourpy=1.0.5
  - cryptography=41.0.2
  - cycler=0.11.0
  - dbus=1.13.18
  - debugpy=1.6.7
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - et_xmlfile=1.1.0
  - expat=2.4.9
  - fontconfig=2.14.1
  - fonttools=4.25.0
  - freetype=2.12.1
  - giflib=5.2.1
  - glib=2.69.1
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - icu=58.2
  - idna=3.4
  - intel-openmp=2021.4.0
  - ipython_genutils=0.2.0
  - jinja2=3.1.2
  - jpeg=9e
  - json5=0.9.6
  - jupyter=1.0.0
  - jupyter_client=7.4.9
  - jupyter_console=6.6.3
  - jupyter_core=5.3.0
  - jupyter_server=1.13.5
  - jupyterlab=3.3.2
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.10.3
  - jupyterlab_widgets=3.0.5
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang=10.0.1
  - libdeflate=1.17
  - libedit=3.1.20221030
  - libevent=2.1.12
  - libffi=3.4.2
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=11.2.0
  - libllvm10=10.0.1
  - libpng=1.6.39
  - libpq=12.15
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - libtiff=4.5.0
  - libuuid=1.41.5
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxcb=1.15
  - libxkbcommon=1.0.1
  - libxml2=2.9.14
  - libxslt=1.1.35
  - lxml=4.9.1
  - lz4-c=1.9.4
  - matplotlib=3.7.1
  - matplotlib-base=3.7.1
  - matplotlib-inline=0.1.6
  - mistune=0.8.4
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - munkres=1.1.4
  - nbclassic=0.5.5
  - nbclient=0.5.13
  - nbconvert=6.5.4
  - ncurses=6.4
  - notebook=6.5.4
  - notebook-shim=0.2.2
  - nspr=4.35
  - nss=3.89.1
  - numexpr=2.8.4
  - numpy=1.24.3
  - numpy-base=1.24.3
  - openpyxl=3.0.10
  - openssl=1.1.1u
  - packaging=23.0
  - pandas=1.5.3
  - pandocfilters=1.5.0
  - parso=0.8.3
  - patsy=0.5.3
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.4.0
  - pip=23.0.1
  - ply=3.11
  - pooch=1.4.0
  - prometheus_client=0.14.1
  - prompt_toolkit=3.0.36
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.15.1
  - pyopenssl=23.2.0
  - pyparsing=3.0.9
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - python=3.11.3
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - pytz=2022.7
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtconsole=5.4.2
  - qtpy=2.2.0
  - qtwebkit=5.212
  - readline=8.2
  - requests=2.31.0
  - scipy=1.10.1
  - seaborn=0.12.2
  - send2trash=1.8.0
  - setuptools=66.0.0
  - sip=6.6.2
  - six=1.16.0
  - soupsieve=2.4
  - sqlite=3.41.2
  - stack_data=0.2.0
  - statsmodels=0.14.0
  - terminado=0.17.1
  - tinycss2=1.2.1
  - tk=8.6.12
  - toml=0.10.2
  - tornado=6.3.2
  - typing-extensions=4.7.1
  - typing_extensions=4.7.1
  - tzdata=2023c
  - webencodings=0.5.1
  - websocket-client=0.58.0
  - wheel=0.38.4
  - xz=5.2.10
  - zeromq=4.3.4
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - anyio==3.7.1
      - arrow==1.2.3
      - arviz==0.16.1
      - asttokens==2.2.1
      - async-generator==1.10
      - attrs==23.1.0
      - binaryornot==0.4.4
      - blosc2==2.3.1
      - cachetools==5.3.1
      - certifi==2023.5.7
      - chardet==5.2.0
      - charset-normalizer==3.2.0
      - click==8.1.6
      - cloudpickle==2.2.1
      - comm==0.1.3
      - cons==0.4.6
      - cookiecutter==2.2.3
      - cvxpy==1.3.2
      - ecos==2.0.12
      - etuples==0.3.9
      - exceptiongroup==1.1.1
      - executing==1.2.0
      - fastjsonschema==2.18.0
      - fastprogress==1.0.3
      - filelock==3.12.2
      - gdown==4.7.1
      - h11==0.14.0
      - h5netcdf==1.2.0
      - h5py==3.9.0
      - html5lib==1.1
      - humanize==4.7.0
      - ipykernel==6.25.0
      - ipython==8.14.0
      - ipyvue==1.9.2
      - ipyvuetify==1.8.10
      - ipywidgets==8.1.0
      - jedi==0.19.0
      - joblib==1.3.1
      - jsonschema==4.18.4
      - jsonschema-specifications==2023.7.1
      - jupyter-client==8.3.0
      - jupyter-core==5.3.1
      - jupyterlab-widgets==3.0.8
      - logical-unification==0.4.6
      - markdown==3.4.4
      - markdown-it-py==3.0.0
      - markupsafe==2.1.3
      - mdurl==0.1.2
      - mesa==2.1.1
      - minikanren==1.0.3
      - msgpack==1.0.7
      - multipledispatch==1.0.0
      - nbformat==5.9.2
      - ndindex==1.7
      - nest-asyncio==1.5.7
      - networkx==3.1
      - osqp==0.6.3
      - outcome==1.2.0
      - platformdirs==3.10.0
      - prompt-toolkit==3.0.39
      - psutil==5.9.5
      - py-cpuinfo==9.0.0
      - pymc==5.7.0
      - pymc-experimental==0.0.9
      - pymdown-extensions==10.1
      - pypdf2==3.0.1
      - pytensor==2.14.1
      - python-graphviz==0.20.1
      - python-slugify==8.0.1
      - pyyaml==6.0.1
      - pyzmq==25.1.0
      - qdldl==0.1.7.post0
      - reacton==1.7.1
      - referencing==0.30.0
      - rich==13.5.2
      - rich-click==1.6.1
      - rpds-py==0.9.2
      - scikit-learn==1.3.0
      - scs==3.2.3
      - selenium==4.9.1
      - sniffio==1.3.0
      - solara==1.19.0
      - sortedcontainers==2.4.0
      - stack-data==0.6.2
      - starlette==0.31.0
      - tables==3.9.1
      - text-unidecode==1.3
      - threadpoolctl==3.2.0
      - toolz==0.12.0
      - tqdm==4.65.0
      - traitlets==5.9.0
      - trio==0.22.0
      - trio-websocket==0.10.2
      - urllib3==2.0.2
      - uvicorn==0.23.2
      - watchdog==3.0.0
      - wcwidth==0.2.6
      - websockets==11.0.3
      - widgetsnbextension==4.0.8
      - workadays==2022.8.8
      - wsproto==1.2.0
      - xarray==2023.7.0
      - xarray-einstats==0.6.0
